[package]
name = "thermometer"
version = "0.0.2"
authors = ["Robert Vojta <zrzka@users.noreply.github.com>"]

[dependencies]
chrono = "0.4"
clap = "2"
piston_window = "0.80"
find_folder = "0.3.0"
lazy_static = "1"

[features]
default = []
simulate-temperature = []
